version: '2'
services:
  wordpress:
    image: visiblevc/wordpress:latest
    links:
      - db
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./dist/data:/data # Required if importing an existing database
      - ./dist/wp-content/uploads:/app/wp-content/
      # - ./yourplugin:/app/wp-content/plugins/yourplugin # Plugin development
      - ./dist/bienen:/app/wp-content/themes/Anna   # Theme development
    environment:
      DB_HOST: db
      DB_NAME: wordpress
      DB_PASS: root # must match below
      PLUGINS: >-
        wp-migrate-db,
        [WP-API-master]https://github.com/WP-API/WP-API/archive/master.zip,
      SEARCH_REPLACE: yoursite.com,localhost:8080
      WP_DEBUG: 'true'
  db:
    image: mysql:5.7 # or mariadb:10
    ports:
      - 3306:3306
    volumes:
      - ./dist/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data: {}